site_name: RhinoInsideCadwork
repo_url: https://github.com/Brunner246/RhinoInsideCadwork

# Copyright
copyright: Copyright &copy; 2021 cadwork 

theme:
    name: material
    nav_style: dark
    logo: cw_logo.svg
    version: v28
    palette:
    - scheme: default
      toggle:
        name: Switch to light mode
        icon: material/weather-sunny
    - scheme: slate
      #primary: grey
      #accent: blue
      toggle:
        name: Switch to dark mode
        icon: material/weather-night
    features:
    - content.code.annotate
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

markdown_extensions:
  - attr_list  
  - footnotes:
      SEPARATOR: _footnote_
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  generator: false
  copyright: Copyright & copy; 2021 cadwork
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Brunner246
      name: RhinoInsideCadwork
  alternate:
    - name: Deutsch
      link: ./de/
      lang: de
    - name: Français
      link: ./fr/
      lang: fr
    - name: English
      link: ./en/
      lang: en
extra_css:
  - extra/svg.css
extra_css:
  - stylesheets\extra.css

plugins:
  - search:
      separator: '[\s\-\.\_]+'  
  - i18n:
      default_language: de
      languages:
        de: Deutsch
        fr: Français   
        en: English 
      nav_translations:
        fr:
          Attribute: Attribute
          Elemente: Elements
          Architektur: Architecture
        en:
          Attribute: Attribute
          Elemente: Elements
          Architektur: Architecture
